version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
     

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: NewBackend
    env_file: ./.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: NewFrontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api